### PR TITLE
Modification updates

### PR DESCRIPTION
**Pull request by VasaviLagishetty**
modification1
modification2

### CODE REVIEW

**Comment by SriSatyaLokesh** [comment]
In your next PR please make a small change.
move social icons to footer.
below that arrow.

**Review by puneethkanna — APPROVED** [review]
Everything is okay. Does everything working asusal after the changes.

**Review by SriSatyaLokesh — APPROVED** [review]

**Comment by SriSatyaLokesh** [comment]
> Everything is okay. Does everything working asusal after the changes.

Is there any way to automate this? (like testing)

**Comment by puneethkanna** [comment]
> > Everything is okay. Does everything working asusal after the changes.
> 
> Is there any way to automate this? (like testing)

Will check it.

**Comment by puneethkanna** [comment]
> > > Everything is okay. Does everything working asusal after the changes.
> > 
> > 
> > Is there any way to automate this? (like testing)
> 
> Will check it.

https://github.com/seleniumbase/SeleniumBase
Here I found a tool, I will try it once.

**Pull request merged**
